version: 2

jobs:
  install:
    docker:
      - image: circleci/node:8.7

    steps:
      - checkout

      - restore_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install node dependencies
          command: |
            if [ ! -d ./node_modules ]; then
              yarn --pure-lockfile
            fi
      - save_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - run:
          name: Install bower dependencies
          command: |
            yarn global add bower
            npx bower i
      - save_cache:
          key: bower-deps-{{ checksum "bower.json" }}
          paths:
            - ./bower_components

  test:
    docker:
      - image: circleci/node:8.7-browsers
        environment:
          JOBS: 2

    steps:
      - checkout
      - restore_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - run:
          name: Test
          command: npx ember test

  deploy:
    docker:
      - image: circleci/node:8.7
        environment:
          JOBS: 2
    steps:
      - checkout
      - restore_cache:
          key: v2-node8-yarn-deps-{{ arch }}-{{ checksum "yarn.lock" }}
      - restore_cache:
          key: bower-deps-{{ checksum "bower.json" }}
      - run:
          name: Deploy to GitHub Pages
          command: |
            git checkout gh-pages; git checkout master
            npx ember deploy production

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
